# Replace 'my_db_name' with the name you just created in pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/backendKMS
spring.datasource.username=postgres
spring.datasource.password=2529

# This tells Hibernate to automatically create tables based on your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=sanpan2529@gmail.com
spring.mail.password=ryyd rofl dwax fwte
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

# ADD ONLY THESE TO FIX THE CERTIFICATE ERROR
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2



# 256-bit Secret Key for HS256 algorithm
jwt.secret=413f4428472b4b6250655368566d597133743677397a24432646294a404e6352

# Expiration time in milliseconds (10 hours = 36,000,000 ms)
jwt.expiration=1800000

from=sanpan2529@gmail.com
# Shows detailed web request logs
logging.level.org.springframework.web=DEBUG
# Shows SQL errors
logging.level.org.hibernate.SQL=DEBUG
# General debug level for your own code
logging.level.com.kms.backend=DEBUG

